### ISSUE TITLE
Color drop-down menu: color preview

### ISSUE THREAD

**Issue by j-wol** [wakr70/CCU-Historian-HC#7]
Hello,
I am using CCU-Historian-HC v6.9 and have following request: The color drop-down menu in the edit menu shows a list of 40 colors named "Color x" where is [0...39]. Unfortunately, there is no hint what color is behind which is very stressful when you want to select a proper color for your diagram. Therefore I ask you to preview the color as background in the corresponding menu item. Or you can color the text accordingly. From [this diagram](https://github.com/wakr70/CCU-Historian-HC/blob/master/docs/screen5.png) I suggest that this feature were already implemented but it for what ever reason not available in the latest version

**Comment by wakr70** [comment]
Hi j-wol,
which browser you use, on my browsers firefox and edge it is working already with background color in the drop-down menu.

br wak

**Comment by j-wol** [comment]
Hello @wakr70,
I use Firefox 120.0.1 on a Linux Mint 20.3 Cinnamon and Safari browser on a iPad. On both browsers the color is not shown in the drop-down menu.
I just tested it with Chrome on Linux and there the colors are visible in the drop-down menu.
Therefore, seems not to be a general bug on your side but more a browser issue. Nevertheless, do you have any idea what you could potentially adopt to get it work on "my" browsers?

Best regards,
Jan

**Comment by wakr70** [comment]
Hi Jan,

i have also a iPad, but on Safari Browser it is not possible to set background colors in drop-down fields.

I wounder that Firefox 120.0.1 are not showing it on Linux, on Windows my Firefor 121.0, do it perfectly.

The only idea is for me at the moment to create some Favorits on a supported Browser, so you do not need it on the others ... (no good solution, but i have not a better one).
BR wak

**Comment by j-wol** [comment]
Ok, fine. Then let's close the issue.
