### ISSUE TITLE
Feature request: Sort favorite list alphabetically

### ISSUE THREAD

**Issue by j-wol** [wakr70/CCU-Historian-HC#9]
Hello,
could you please improve the CCU Hist. HighChart application by alphabetically sort the favorites list? Currently, a new list item is always added to the end of the favorite list.

**Comment by wakr70** [comment]
Hi j-wol,
sorry i have not seen you issue. You can drag and drop the favorite between different lines. please try!
BR wak

**Comment by j-wol** [comment]
Hi, yes that works. Thanks!
